### ISSUE TITLE
as lists can not be merged in ansible, change list definitions to dict

### ISSUE THREAD

**Issue by zerwes** [zerwes/ansible-role-checkmkagent#12]
... this would make deployment in complex setups easier, as we can define a minimal set of plugins etc. for all, and extend this optionally per host/group etc ...
```yaml
check_mk_logwatch_syslog_patterns: []
checkmkagent_required_packages: []
check_mk_plugins: []
check_mk_local_plugins: []
check_mk_local_cfg: []
```
